// Code generated by go-bindata. DO NOT EDIT.
// sources:
// migrations/000001_account.up.sql (277B)
// migrations/000002_account.down.sql (38B)
// migrations/000003_transfer.up.sql (266B)
// migrations/000004_transfer.down.sql (39B)

package postgres

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __000001_accountUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x54\x90\x31\x4f\xc3\x30\x10\x46\xe7\xf8\x57\x7c\x63\x2b\x75\x08\x88\x4e\x9d\xdc\x72\x05\x8b\xd8\x29\xce\x59\x50\x96\xea\x70\x5c\x11\xa9\x04\x14\x1c\x7e\x3f\xa2\x43\xa3\x8e\xa7\x77\xef\x9e\x74\x6b\x7a\x30\x6e\xa5\xd4\xc6\x93\x66\x02\xeb\x75\x45\x30\x5b\xb8\x9a\x41\xaf\xa6\xe1\x06\x12\xe3\xd7\xd8\x67\x35\x53\x45\xd7\x62\x1c\xbb\x16\x3b\x6f\xac\xf6\x7b\x3c\xd1\x7e\xa1\x8a\x5e\x3e\x13\x7e\x65\x88\x1f\x32\xcc\x6e\x97\xcb\xf9\xd9\x76\xa1\xaa\x16\xaa\x88\xdf\xc7\x0b\xbb\xb9\x9b\x10\x82\x33\xcf\x81\x16\xaa\xf8\x49\x71\x48\x79\x5a\x2a\xcb\xab\x03\xef\x72\x92\x3e\x26\x74\x7d\x46\x9b\x8e\x32\x9e\x32\xca\xab\xc2\x90\x24\xa7\xf6\x20\x19\x6c\x2c\x35\xac\xed\x0e\x2f\x86\x1f\xcf\x23\xde\x6a\x47\x53\xf5\x9e\xb6\x3a\x54\x8c\x4d\xf0\x9e\x1c\x1f\x2e\x86\x9a\xff\x7f\xa1\xb6\xd6\xf0\xea\x2f\x00\x00\xff\xff\x77\x35\xfc\x1e\x15\x01\x00\x00")

func _000001_accountUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_accountUpSql,
		"000001_account.up.sql",
	)
}

func _000001_accountUpSql() (*asset, error) {
	bytes, err := _000001_accountUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_account.up.sql", size: 277, mode: os.FileMode(0644), modTime: time.Unix(1620164746, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x99, 0xc0, 0x2e, 0x38, 0x1, 0xed, 0xe5, 0x38, 0x50, 0x85, 0xe8, 0x3b, 0x0, 0x71, 0x66, 0x68, 0xd3, 0x10, 0x2d, 0x88, 0x29, 0x26, 0x4a, 0xd6, 0x8e, 0xb, 0x17, 0xbd, 0x38, 0x3e, 0xfd, 0x7c}}
	return a, nil
}

var __000002_accountDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x4c\x4e\xce\x2f\xcd\x2b\x51\x70\x76\x0c\x76\x76\x74\x71\xb5\xe6\x02\x04\x00\x00\xff\xff\x28\x19\x2b\xd0\x26\x00\x00\x00")

func _000002_accountDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_accountDownSql,
		"000002_account.down.sql",
	)
}

func _000002_accountDownSql() (*asset, error) {
	bytes, err := _000002_accountDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_account.down.sql", size: 38, mode: os.FileMode(0644), modTime: time.Unix(1620164759, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xac, 0x90, 0x9f, 0xce, 0x7e, 0x76, 0xaa, 0xad, 0x5d, 0xd6, 0x12, 0xc7, 0x31, 0xae, 0xb1, 0xdb, 0x4, 0xa8, 0xff, 0x98, 0xb0, 0x97, 0x19, 0x93, 0x4a, 0x29, 0x44, 0xaa, 0x3b, 0x67, 0x26, 0x9e}}
	return a, nil
}

var __000003_transferUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\xcf\xc1\x4a\xc4\x30\x10\x80\xe1\x73\xf3\x14\x73\x54\xd8\x37\xd8\x53\xb6\x4e\x35\x98\xa4\x25\x99\xa2\xf5\x12\x42\x13\x25\x07\x53\x48\xd3\xf7\x97\x16\x2d\xde\xf6\x36\x03\xdf\x0f\x33\x37\x7c\x16\xfa\xca\x58\x6b\x90\x13\x02\xf1\x9b\x44\x10\x1d\xe8\x9e\x00\xdf\x85\x25\x0b\xb5\xf8\xbc\x7e\xc6\xc2\x1e\x58\x93\x02\x6c\x5b\x0a\x30\x18\xa1\xb8\x99\xe0\x15\xa7\x0b\x6b\xfc\x3c\x2f\x5b\xae\x6e\x29\xe9\x2b\x65\xf7\x87\x0c\x76\x68\x50\xb7\x68\xe1\x57\xfc\xb3\x21\xae\x35\x65\x5f\xd3\x72\x2f\xf8\xde\x07\x48\xb9\x1e\x47\xe9\x51\xca\x0b\x6b\xe6\x12\x7d\x8d\xc1\xf9\x0a\x24\x14\x5a\xe2\x6a\x80\x37\x41\x2f\xc7\x0a\x1f\xbd\xc6\x93\xc3\x13\x76\x7c\x94\x04\xed\x68\x0c\x6a\x72\x67\xc1\x1e\xf7\xd7\x7b\xa5\x04\x5d\x7f\x02\x00\x00\xff\xff\xa9\x13\x27\xe8\x0a\x01\x00\x00")

func _000003_transferUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000003_transferUpSql,
		"000003_transfer.up.sql",
	)
}

func _000003_transferUpSql() (*asset, error) {
	bytes, err := _000003_transferUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000003_transfer.up.sql", size: 266, mode: os.FileMode(0644), modTime: time.Unix(1620411730, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x51, 0x3b, 0x27, 0x9c, 0xf3, 0x85, 0x18, 0x69, 0x27, 0x9b, 0x57, 0x1e, 0x23, 0x61, 0xfe, 0x51, 0xaf, 0x66, 0x83, 0x0, 0x15, 0x39, 0xb, 0x13, 0x9c, 0xe9, 0x46, 0xe6, 0xcd, 0xfe, 0x32, 0x3f}}
	return a, nil
}

var __000004_transferDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x29\x4a\xcc\x2b\x4e\x4b\x2d\x52\x70\x76\x0c\x76\x76\x74\x71\xb5\xe6\x02\x04\x00\x00\xff\xff\x0c\x7f\x29\x9e\x27\x00\x00\x00")

func _000004_transferDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000004_transferDownSql,
		"000004_transfer.down.sql",
	)
}

func _000004_transferDownSql() (*asset, error) {
	bytes, err := _000004_transferDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000004_transfer.down.sql", size: 39, mode: os.FileMode(0644), modTime: time.Unix(1620408078, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xf7, 0xcc, 0x67, 0x85, 0x57, 0xc6, 0xed, 0x8c, 0xe6, 0xb4, 0xb8, 0xc2, 0xc, 0x81, 0x99, 0x59, 0xa3, 0xd9, 0xcb, 0x17, 0x1, 0x33, 0x3e, 0x10, 0xcb, 0x9d, 0x78, 0x5e, 0xf4, 0xc0, 0xa1, 0xb5}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"000001_account.up.sql":    _000001_accountUpSql,
	"000002_account.down.sql":  _000002_accountDownSql,
	"000003_transfer.up.sql":   _000003_transferUpSql,
	"000004_transfer.down.sql": _000004_transferDownSql,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"000001_account.up.sql":    {_000001_accountUpSql, map[string]*bintree{}},
	"000002_account.down.sql":  {_000002_accountDownSql, map[string]*bintree{}},
	"000003_transfer.up.sql":   {_000003_transferUpSql, map[string]*bintree{}},
	"000004_transfer.down.sql": {_000004_transferDownSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
