version: "3.1"

services:
  simple_bank_db:
    container_name: simple_bank_db
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: simple_bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    container_name: simple_bank_api
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      DATABASE_NAME: simple_bank_db
      DATABASE_HOST_DIRECT: simple_bank_db
      HOSTNAME: simple_bank_db

volumes:
  postgres_data: